# ghc 8.8.3
resolver: lts-16.0

packages:
 - .

flags:
 xmobar:
   all_extensions: true
   with_threaded: true

extra-deps:
 - netlink-1.1.1.0
 - libmpd-0.9.2.0
nix:
    packages:
      - alsaLib
      - pkgconfig
      - wirelesstools
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXScrnSaver
      - zlib
